---
version: "3"
tasks:
  # Build
  build:host:
    summary: Build on host
    desc: Build on host
    cmds:
      - mvn clean install -Denforcer.fail=false
  build:container:
    summary: Build in container
    desc: Build in container
    cmds:
      - |
        # Clean
        rm -rf target && mkdir target

        # Build Container
        DOCKER_GROUP_ID=$(getent group docker | cut -d: -f3)
        docker build -f Dockerfile . --build-arg DOCKER_GROUP_ID=$DOCKER_GROUP_ID --progress=plain --sbom=false --provenance=false --tag testbed-maven-builder

        # Build Artifact
        docker run -v .:/app -v $HOME/.m2:/home/maven/.m2 -v /var/run/docker.sock:/var/run/docker.sock --env GITHUB_USER_REF --env GITHUB_TOKEN_REF testbed-maven-builder mvn --batch-mode clean install -Denforcer.fail=false

  tool-versions:upgrade:repo:
    summary: Upgrade version in .tool-versions
    desc: Upgrade version in .tool-versions
    internal: true
    silent: true
    cmds:
      - |
        version=$(gh api -H "Accept: application/vnd.github+json" repos/{{ .OWNER }}/{{ .NAME }}/releases/latest | jq .tag_name -r)
        version=${version//v}
        sed -i "s/{{ .NAME }}.*/{{ .NAME }} $version/g" .tool-versions
  tool-versions:upgrade:
    summary: Upgrade versions in .tool-versions
    desc: Upgrade versions in .tool-versions
    cmds:
      - task: tool-versions:upgrade:trivy
      - task: tool-versions:upgrade:task
  tool-versions:upgrade:trivy:
    summary: Upgrade version of trivy in .tool-versions
    desc: Upgrade version of trivy .tool-versions
    cmds:
      - task: tool-versions:upgrade:repo
        vars:
          OWNER: aquasecurity
          NAME: trivy
  tool-versions:upgrade:task:
    summary: Upgrade version of task in .tool-versions
    desc: Upgrade version of task .tool-versions
    cmds:
      - task: tool-versions:upgrade:repo
        vars:
          OWNER: go-task
          NAME: task
  semgrep:auto:
    summary: Run semgrep static analysis with auto config
    desc: Run semgrep static analysis with auto config
    silent: true
    cmds:
      - semgrep --config=auto .
  semgrep:security-audit:
    summary: Run semgrep static analysis with security-audit config
    desc: Run semgrep static analysis with security-audit config
    silent: true
    cmds:
      - semgrep --config=p/security-audit .
  semgrep:secrets:
    summary: Run semgrep static analysis with secrets config
    desc: Run semgrep static analysis with secrets config
    silent: true
    cmds:
      - semgrep --config=p/secrets .
  trivy:fs:
    summary: Run trivy fs check
    desc: Run trivy fs check
    silent: true
    cmds:
      - trivy fs .
  trivy:config:
    summary: Run trivy config check
    desc: Run trivy config check
    silent: true
    cmds:
      - trivy config .
