name: Publish package
on:
  push:
    branches:
      - "master"
jobs:
  build:
    permissions:
      contents: write
      packages: write
    uses: aps831/workflows/.github/workflows/publish-maven-in-docker-artificat.yaml@refactor/build-release
    with:
      prerelease-branch: "prerelease"
      update-branch: "chore/publish-update"
      tag-prefix: "v"
      templated-files: ""
      settings-file: ""
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
