name: Publish package
on:
  push:
    branches:
      - "master"
jobs:
  build:
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
    uses: aps831/workflows/.github/workflows/publish-maven-in-docker-artificat.yaml@refactor/build-release
    with:
      prerelease-branch: "prerelease"
      update-branch-base: "chore/publish-update"
      tag-prefix: "v"
      templated-files: "README.tpl.md"
      settings-file: ""
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
